[project]
name = "quantum-challenges"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
  "qiskit>=1.0.0",
  "cirq>=1.3",
  "matplotlib",
  "numpy",
  "pytest",
  "ruff",
  "pre-commit",
]

[tool.ruff]
line-length = 100
